### PR TITLE
Adding python 3.4 support.

### PR DESCRIPTION
**Pull request by pyghassen**
I'm already using it in my Django 1.7 project on python 3.4, no issues so far.

### CODE REVIEW

**Comment by swistakm** [comment]
I have fixed this branch and merged. Now master should pass all tests on travis.

**Comment by pyghassen** [comment]
Good job @swistakm what version these changes are merged to?

**Comment by swistakm** [comment]
it's merged to master. You can find latest version under v1.4.0 tag, but for new release we need to wait until @wunki decides to put it in PyPI

**Comment by pyghassen** [comment]
Ok then I will wait for @wunki to put it on PyPi so I can remove the dependence from my github fork, and go back using pip's latest one.

**Comment by wunki** [comment]
Latest version is on PyPi.

**Pull request merged**
