### PR TITLE
Django 1.9 compatibility fixes

### PR DESCRIPTION
**Pull request by smlz**
Some commits that makes django-userena work with Django 1.9.

Django 1.4 compatibility had to be dropped (`{% load url from future %}` was removed from Django 1.9).

So far, the changes seem to work fine, but some more testing is certainly needed before making a release.

### CODE REVIEW

**Comment by swistakm** [comment]
Great. Thank you very much for contribution. I will need some time to make an in-depth review but this is great that you found time to make such upgrade. First things that I noticed are:
* `.travis.yml` tox environments for django1.4 should be removed too to make CI tests pass
* we could remove any other django1.4 compatibility quirks (see `compat.py` module)

Since we are dropping django 1.4 I will have to prepare new userena==2.0.0 release and this will go there. I'm also not familiar with django1.9 yet so this will take some more time because I'm concerned about migrations.

**Comment by smlz** [comment]
Ok, I fixed the coverage and travis configs, and removed some obsolete compatibility code.

I'd probably go with 1.5. But that's just a matter of taste.

Anyway, I also had look at some DeprecationWarnings for things that are going to be removed with the next LTS release of Django (see https://www.djangoproject.com/weblog/2015/jun/25/roadmap/). With these changes your planned upcoming release would stay compatible with Django up to version 1.11. Theoretically ;-)

**Comment by swistakm** [comment]
I have merged it to v2.0.x branch because I would like to introduce some other improvements that will break backwards compatibility in 2.0.0 version before first release.

**Comment by AmmsA** [comment]
Sorry to jump in but any idea when will the v2.0.x version will be released?

**Comment by swistakm** [comment]
I will try to do it in week or two because I need to do some code cleanup and I have very limited time for this project.

**Comment by swistakm** [comment]
Merged from v2.0.x branch

**Pull request closed without merging**
