### PR TITLE
Romanian translations

### PR DESCRIPTION
**Pull request by aramboi**

### CODE REVIEW

**Comment by swistakm** [comment]
@aramboi thanks for contribution!

 I don't know why build failed for django 1.4. It should not because this affects only translations. It seems that it userena is broken with new version of `django-guardian` that was released recently.

So I merge it because it is safe but this will be released only when I figure out how to handle this broken build situation.

**Comment by aramboi** [comment]
Seems like `django-guardian` dropped support for Django below 1.5 with the latest 1.3.2 version. Commit:
https://github.com/django-guardian/django-guardian/commit/35f631491ad5567b0bfc32d5a3d9fd6fcf46b60c

For me it's not an issue as I don't need the translations right away. I actually created them quite a while ago and forgot, then found them a few days ago, cleaned them a bit and pushed the PR. :)

**Comment by aramboi** [comment]
I think this is mainly because support ended for Django 1.4 LTS on October 1.

**Comment by swistakm** [comment]
Yeah i noticed that change but I think no package should do such things in a point release. We will also eventually drop django 1.4 but we definitely won't go that way. Such things deserve major or at least minor version release.

Shame on you django-guardian!

**Comment by aramboi** [comment]
I agree. Backwards incompatible changes shouldn't be part of a minor releases. Then again that is up to the package maintainers and their release policy.

**Pull request merged**
